# Generated by Django 5.0.6 on 2024-06-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('description', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('priority', models.CharField(max_length=50)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
